(defcaixa
  :name
  "lava-helm"
  :kind
  :Biblioteca
  :ecosystem
  :rust-single-crate
  :package
  {:name "lava-helm"
   :version "0.1.0"
   :description "Tatara-lisp typed surface for helm resources. Auto-generated by lava-forge from the helm TF provider schema. Pangea-helm analog."
   :license "MIT"
   :repository "https://github.com/pleme-io/lava-helm"}
  :ci-config
  {:bump {:default-type "patch"}
   :publish {:no-verify true}}
  :workflows
  [:auto-release :pre-merge-gate :security-gate])
