# nix/modules/nixos.nix — auto-generated from lava-helm.caixa.lisp
# description: "Tatara-lisp typed surface for helm resources. Auto-generated by lava-forge from the helm TF provider schema. Pangea-helm analog."
{ config, lib, pkgs, ... }:
let
  cfg = config.services.lava-helm;
in {
  options.services.lava-helm = {
    enable = lib.mkEnableOption "lava-helm";
    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.lava-helm or null;
    };
  };
  config = lib.mkIf cfg.enable {
    environment.systemPackages = [ cfg.package ];
  };
}
